"""Initial migration.

Revision ID: 402cef531e46
Revises: 
Create Date: 2021-02-09 16:37:52.085182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '402cef531e46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('about_meta_description', sa.Text(), nullable=True),
    sa.Column('about_meta_keywords', sa.Text(), nullable=True),
    sa.Column('about_title', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('num', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('uploded_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.Text(), nullable=True),
    sa.Column('Email', sa.Text(), nullable=True),
    sa.Column('Subject', sa.Text(), nullable=True),
    sa.Column('Message', sa.Text(), nullable=True),
    sa.Column('contact_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_meta_description', sa.Text(), nullable=True),
    sa.Column('index_meta_keywords', sa.Text(), nullable=True),
    sa.Column('index_title', sa.Text(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('blog_meta_description', sa.Text(), nullable=True),
    sa.Column('blog_meta_keywords', sa.Text(), nullable=True),
    sa.Column('blog_title', sa.Text(), nullable=True),
    sa.Column('slug', sa.Text(), nullable=True),
    sa.Column('textarea', sa.Text(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('sign_up',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('login_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sign_up')
    op.drop_table('posts')
    op.drop_table('index')
    op.drop_table('contact')
    op.drop_table('category')
    op.drop_table('about')
    # ### end Alembic commands ###
